### ISSUE TITLE
[reproduce] Which version of Boost library does the code use?

### ISSUE THREAD

**Issue by jixxiong** [jermp/2i_bench#2]
I used Boost version 1.83.0 in this project, but it seems to have encountered many compilation errors. So, I'm wondering which version of Boost I should use to reproduce the results in the paper.

**Comment by jermp** [comment]
Hello,
I do not remember the exact version of Boost I used (I was running the code in 2019).
Boost 1.6 should work. It's hard to say exactly given that I do not know what compilation errors you get.

**Comment by jixxiong** [comment]
> Hello, I do not remember the exact version of Boost I used (I was running the code in 2019). Boost 1.6 should work. It's hard to say exactly given that I do not know what compilation errors you get.

Thanks, it works fine with Boost 1.66.0.
